[tool.poetry]
name = "json-sql"
version = "0.1.0"
description = "Run SQL queries on JSON files"
authors = ["Bruno Vieira Costa <bruno@abstra.app>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
