# Ruff configuration for abstra-json-sql

# Exclude common directories
exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]

# Target Python 3.8+
target-version = "py38"

# Line length
line-length = 88

[lint]
# Enable pycodestyle (E, W), pyflakes (F), and isort (I)
select = ["E", "F", "W", "I"]

# Ignore specific rules
ignore = [
    "E501",  # Line too long (handled by formatter)
]

[format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"
